package com.andy;

public enum TokenKind {
    Str,
    EOF,
    Cls,
    Whitespace,
    Comma,
    Semicolon,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    LineComment,
    If,
    Else,
    ElseIf,
    While,
    For,
    Do,
    Equality,
    Assignment,
    LeftParenthesis,
    RightParenthesis,
    Ident,
    KeywordNew,
    SubItemOperator, // .
    ImportKeyword,
    PublicAccessModifier,
    PrivateAccessModifier,
    ProtectedAccessModifier,
    PackageKeyword,
    TryKeyword,
    CatchKeyword,
    NotEqualsOperator,
    MethodReferenceOperator,
    LessThan, // note the lexer will not worry about generics!
    GreaterThan, // note the lexer will not worry about generics!
    LessThanOrEqualTo,
    GreaterThanOrEqualTo,
    LambdaArrow,
    Colon,
    Numeric,
    LogicalAnd,
    LogicalOr,
    LogicalNot,
    NullKeyword,
    BinaryAnd,
    BinaryOr,
    BinaryXor,
    BinaryShiftLeft,
    BinaryShiftRight,
    BinaryComplement,
    AdditionOperand,
    SubtractionOperand,
    DivisionOperand,
    MultiplicationOperand,
    RangeBasedComment,
    Annotation,
    Character,
    Modulus,
}
